org.gradle.jvmargs=-Xmx3G -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.252
neo_version_range=[21.1.209,)
loader_version_range=[4,)

mod_id=dawnduskterminal
mod_name=DawnDuskTerminal Chrono
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.dawnduskterminal
mod_authors=DawnDuskTerminal Team
mod_description=Chrono dimension with a coord driven terminator line
