org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.72
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=ysm
mod_name=YSM Chrono
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.ysm
mod_authors=ysm
mod_description=Chrono dimension with a coord driven terminator line
